//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizEngine.AssemblyResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizEngine.AssemblyResources.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Quiz.
        /// </summary>
        public static string AdminDownloadGeneratedTest_aspx {
            get {
                return ResourceManager.GetString("AdminDownloadGeneratedTest.aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Template.
        /// </summary>
        public static string AdminDownloadPredefinedTest_aspx {
            get {
                return ResourceManager.GetString("AdminDownloadPredefinedTest.aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Quiz.
        /// </summary>
        public static string FreeTextQuestionsPendingAdminResponse_aspx {
            get {
                return ResourceManager.GetString("FreeTextQuestionsPendingAdminResponse.aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string GenerateQuiz_aspx {
            get {
                return ResourceManager.GetString("GenerateQuiz.aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string ManageCategories_aspx {
            get {
                return ResourceManager.GetString("ManageCategories.aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string ManageLevels_aspx {
            get {
                return ResourceManager.GetString("ManageLevels.aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string ManageQuestions_aspx {
            get {
                return ResourceManager.GetString("ManageQuestions.aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string ManageTags_aspx {
            get {
                return ResourceManager.GetString("ManageTags.aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string ManageUsers_aspx {
            get {
                return ResourceManager.GetString("ManageUsers.aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Quiz.
        /// </summary>
        public static string QuizGenerate_aspx {
            get {
                return ResourceManager.GetString("QuizGenerate.aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string QuizHistory_aspx {
            get {
                return ResourceManager.GetString("QuizHistory.aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Quizzes.
        /// </summary>
        public static string ScoreQuizzes_aspx {
            get {
                return ResourceManager.GetString("ScoreQuizzes.aspx", resourceCulture);
            }
        }
    }
}
